//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class API_MASEntities : DbContext
    {
        public API_MASEntities()
            : base("name=API_MASEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<EM_Info> EM_Info { get; set; }
        public DbSet<Fair_Chart> Fair_Chart { get; set; }
        public DbSet<Payment_Info> Payment_Info { get; set; }
        public DbSet<Pending_Tickets> Pending_Tickets { get; set; }
        public DbSet<Route_List> Route_List { get; set; }
        public DbSet<Salary_Info> Salary_Info { get; set; }
        public DbSet<Token> Tokens { get; set; }
        public DbSet<Token_Info> Token_Info { get; set; }
        public DbSet<Train_List> Train_List { get; set; }
        public DbSet<Train_Schedule> Train_Schedule { get; set; }
        public DbSet<User_Info> User_Info { get; set; }
        public DbSet<Purchase_Tickets> Purchase_Tickets { get; set; }
    }
}
