//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pending_Tickets
    {
        public Pending_Tickets()
        {
            this.Purchase_Tickets = new HashSet<Purchase_Tickets>();
        }
    
        public int Tkt_ID { get; set; }
        public int User_ID { get; set; }
        public string Start_Station { get; set; }
        public string End_Station { get; set; }
        public string Date { get; set; }
        public string Time { get; set; }
        public string Train_Name { get; set; }
        public string Psn_Num { get; set; }
        public string Psn_Type { get; set; }
        public string Coach_Type { get; set; }
        public string Coach_Num { get; set; }
        public string Sit_01 { get; set; }
        public string Sit_02 { get; set; }
        public string Sit_03 { get; set; }
        public string Sit_04 { get; set; }
        public string Cost { get; set; }
        public string Status { get; set; }
    
        public virtual User_Info User_Info { get; set; }
        public virtual ICollection<Purchase_Tickets> Purchase_Tickets { get; set; }
    }
}
