//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Purchase_Tickets
    {
        public int Tkt_ID { get; set; }
        public int User_ID { get; set; }
        public string Start_Station { get; set; }
        public string End_Station { get; set; }
        public string Time { get; set; }
        public string Date { get; set; }
        public string Train_Name { get; set; }
        public string Coach_Number { get; set; }
        public string Sit_01 { get; set; }
        public string Sit_02 { get; set; }
        public string Sit_03 { get; set; }
        public string Sit_04 { get; set; }
        public string Status { get; set; }
    
        public virtual Pending_Tickets Pending_Tickets { get; set; }
        public virtual User_Info User_Info { get; set; }
    }
}
