//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Route_List
    {
        public Route_List()
        {
            this.Fair_Chart = new HashSet<Fair_Chart>();
            this.Train_Schedule = new HashSet<Train_Schedule>();
        }
    
        public int Route_ID { get; set; }
        public string Route_Name { get; set; }
        public string Route_Code { get; set; }
        public string SM_Name { get; set; }
    
        public virtual ICollection<Fair_Chart> Fair_Chart { get; set; }
        public virtual ICollection<Train_Schedule> Train_Schedule { get; set; }
    }
}
