//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Salary_Info
    {
        public int Salary_ID { get; set; }
        public int User_ID { get; set; }
        public string Name { get; set; }
        public string Role { get; set; }
        public string Salary { get; set; }
    
        public virtual User_Info User_Info { get; set; }
    }
}
