//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Train_List
    {
        public Train_List()
        {
            this.Train_Schedule = new HashSet<Train_Schedule>();
        }
    
        public int Train_ID { get; set; }
        public string Train_Name { get; set; }
        public string Start_Station { get; set; }
        public string End_Station { get; set; }
        public string Train_Master { get; set; }
    
        public virtual ICollection<Train_Schedule> Train_Schedule { get; set; }
    }
}
