//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Train_Schedule
    {
        public int Schedule_ID { get; set; }
        public int Route_ID { get; set; }
        public string Route_Name { get; set; }
        public int Train_ID { get; set; }
        public string Train_Name { get; set; }
        public string Start_Time { get; set; }
        public string End_Time { get; set; }
    
        public virtual Route_List Route_List { get; set; }
        public virtual Train_List Train_List { get; set; }
    }
}
